stages:
  - check
  - build

default:
  image: python:3.9
  before_script:
    - if [ ! -e .poetry/bin/poetry ] ; then
    -   curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | HOME=$PWD python -
    - fi
    - export PATH=$PWD/.poetry/bin:$PATH
    - poetry config --local cache-dir $PWD/.poetry/cache
    - poetry config --local virtualenvs.in-project true
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .poetry
      - .venv

check-linters:
  stage: check
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_COMMIT_BRANCH =~ /ci$/
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'master'
  script:
    - poetry install
    - echo "Checking with Flake8"
    - flake8 .
    - echo "Checking with MyPy"
    - mypy .


tests:
  stage: check
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_COMMIT_BRANCH =~ /ci$/
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'master'
  script:
    - poetry install
    - echo "Run tests"
    - pytest .


build-release:
  image: python:3.8
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Building to python package"
    - poetry build
  artifacts:
    expire_in: never
    paths:
      - $CI_PROJECT_DIR/dist
