default_stages:
  - commit
  - push
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast
      - id: check-merge-conflict
        stages:
          - commit
  - repo: https://github.com/python/black
    rev: 23.1.0
    hooks:
      - id: black
        stages:
          - commit
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        stages:
          - commit
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - additional_dependencies:
          - yastyleguide==0.2.0
        id: flake8
        stages:
          - commit
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.1
    hooks:
      - id: commitizen
        stages:
          - commit-msg
  - repo: https://github.com/andreoliwa/nitpick
    rev: v0.32.0
    hooks:
      - additional_dependencies:
          - requests-cache==0.9.8
        id: nitpick
